

name = "saz-hamed-panel"
main = "_worker.js"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "IOT_DB"
database_name = "hamed-panel-db"
database_id = "PASTE_YOUR_DATABASE_ID_HERE"


[triggers]
crons = ["*/15 * * * *"]  # هر ۱۵ دقیقه


[observability]
enabled = true

[observability.logs]
invocation_logs = true


[env.production]
name = "saz-hamed-panel"
